apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-nextcloud-b2
  namespace: nextcloud
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: k8up-restic-b2-repo-pw
      key: password
    b2:
      bucket: nextcloud-pgsql
      accountIDSecretRef:
        name: k8up-restic-b2-creds-nextcloud-pg
        key: application-key-id
      accountKeySecretRef:
        name: k8up-restic-b2-creds-nextcloud-pg
        key: application-key
