apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-nextcloud-b2
  namespace: nextcloud
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: k8up-restic-b2-repo-pw
      key: password
    b2:
      bucket: nextcloud-pgsql
      accountIDSecretRef:
        name: k8up-restic-b2-creds-nextcloud-pg
        key: application-key-id
      accountKeySecretRef:
        name: k8up-restic-b2-creds-nextcloud-pg
        key: application-key
  backup:
    # daily at midnight
    schedule: '0 0 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '0 1 * * 1'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    # monthly
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
